### ISSUE TITLE
is it possible to train multiple concepts simultaneously now?

### ISSUE THREAD

**Issue by sincerity11** [Linaqruf/kohya-trainer#123]
I have always processed the dataset and tagged the pictures locally. 
Following this guide, I created several concept subfolders with different repetitions under the 'train_data_dir'. 
![image](https://user-images.githubusercontent.com/37372648/223688962-a7703195-b405-4cbe-b871-4c7f66885e76.png)
This method worked well in the previous version but not in the latest version.

**Comment by Linaqruf** [comment]
Hi, it's still possible for train multiple concepts but just need more work, because colab aren't compatible with the latest changes, but not using `--dataset_config` means we will facing folder naming scheme again. 

Instead of editing markdown, you can edit `dataset_config.toml` created in `5.3. Dataset Config` cell and add nesting for dataset and dataset.subset

for example this is my `dataset_config.toml` : https://huggingface.co/Linaqruf/namazu/blob/main/namazu_locon_db_config/dataset_config.toml

```toml
[[datasets]]
resolution = 512
min_bucket_reso = 256
max_bucket_reso = 1024
caption_dropout_rate = 0
caption_tag_dropout_rate = 0
caption_dropout_every_n_epochs = 0
flip_aug = false
color_aug = false

  [[datasets.subsets]]
  image_dir = "/content/LoRA/train_data/concept_1"
  class_tokens = "mksks  style"
  num_repeats = 10
  
  [[datasets.subsets]]
  is_reg = true
  image_dir = "/content/LoRA/reg_data"
  class_tokens = " style"
  num_repeats = 1

[general]
enable_bucket = true
caption_extension = ".txt"
shuffle_caption = true
keep_tokens = 0
bucket_reso_steps = 64
bucket_no_upscale = false
```

now i want to add new dataset folder, you can create new subset by copying above config, and it will gonna be like this

```toml
  [[datasets.subsets]]
  image_dir = "/content/LoRA/train_data/concept_1"
  class_tokens = "mksks  style"
  num_repeats = 10

# this is new dataset subset folder
  [[datasets.subsets]]
  image_dir = "/content/LoRA/train_data/concept_12"
  class_tokens = "sls frog"
  num_repeats = 10
  
  [[datasets.subsets]]
  is_reg = true
  image_dir = "/content/LoRA/reg_data"
  class_tokens = " style"
  num_repeats = 1
```

For further information, you can read this [guide](https://github.com/kohya-ss/sd-scripts/blob/main/config_README-ja.md). 
With this new update you can also train on different resolution on each dataset subset, or whether you want to use `--random_crop`, not `--enable_bucket` for certain dataset, or anything. More flexible. But just not familiar for colab.

I hope you understand
