### ISSUE TITLE
Issue with training data

### ISSUE THREAD

**Issue by oroshi-zu2473** [Linaqruf/kohya-trainer#174]
Please forgive the machine translation.

I am currently facing two issues

I have two issues at the moment:

1.The "image count" function is not working properly.
It is counting fewer images than what is in the image directory, and as a result, tagging and training are not being performed for all images.

2.During training, spaces and commas are disappearing from the caption file, causing all words to be concatenated together.
During training, for some reason, the following phenomenon occurs:
Example: 1girl, solo, long hair, looking at viewer → 1girlsololonghairlookingatviewer

I would appreciate it if you could provide me with a solution.

**Comment by Linaqruf** [comment]
Hi, can you explain more about the issue you are facing so we can help you reproduce the error? Please provide the following information:

- `dataset_config.toml`
- `config_file.toml`
- Train data folder structure
- Which noteboook?
- Etc

Let me assume that you are facing a frequent issue first

1. >.The "image count" function is not working properly.
It is counting fewer images than what is in the image directory, and as a result, tagging and training are not being performed for all images.

The problem is probably related to the supported train data extension. The image extension supported in the Kohya script is `[".png", ".jpg", ".jpeg", ".webp", ".bmp"]` as stated in `train_util.py`: https://github.com/Linaqruf/kohya-trainer/blob/138a02874a1eb11ec9e14c386fd85c9da078a5a4/library/train_util.py#L74-L79

Another reason could be the train data folder structure. Currently, recursive is not supported in this notebook. If your folder structure is like this:
```
one-piece-lora
├── 10_concept1
│   ├── image1.jpg
│   ├── image2.jpg
│   └── image3.jpg
└── 20_concept2
    ├── image1.jpg
    ├── image2.jpg
    └── image3.jpg
```
If you set `train_data_dir` to `one-piece-lora`, you cannot do tagging for images inside `10_concept1` and `20_concept2`, because it's not recursive, either for scraping, tagging, or even training. This is probably why the image count is not working correctly, because images inside subfolders cannot be reached.

I suggest doing manual data preprocessing if you are facing this issue. For example, set `train_data_dir` to `10_concept1` first, and do data preprocessing (cleaning, tagging). After that, you can do the same thing with `20_concept2`. To train with multiple folders, you cannot set `train_data_dir` to the parent directory. Instead, you can edit `dataset_config.toml`, like this:

```toml
...
        # this is concept1 dataset
        [[datasets.subsets]]
        image_dir = "/content/LoRA/concept1"
        class_tokens = "bocchi"
        num_repeats = 10

        # this is concept2 dataset
        [[datasets.subsets]]
        image_dir = "/content/LoRA/concept2"
        class_tokens = "nijika"
        num_repeats = 5

        # this is concept3 dataset
        [[datasets.subsets]]
        image_dir = "/content/LoRA/concept3"
        class_tokens = "ryo"
        num_repeats = 10

        # this is regularization images folder, optional
        [[datasets.subsets]]
        is_reg = true
        image_dir = "/content/LoRA/reg_data"
        class_tokens = " style"
        num_repeats = 1
...
```
2. >During training, spaces and commas are disappearing from the caption file, causing all words to be concatenated together.
During training, for some reason, the following phenomenon occurs:
Example: 1girl, solo, long hair, looking at viewer → 1girlsololonghairlookingatviewer


Which cell is this? Because I couldn't reproduce the same error too.
